<?php

use Behat\Behat\Context\ClosuredContextInterface,
    Behat\Behat\Context\TranslatedContextInterface,
    Behat\Behat\Context\BehatContext,
    Behat\Behat\Exception\PendingException;
use Behat\Gherkin\Node\PyStringNode,
    Behat\Gherkin\Node\TableNode;

use Behat\MinkExtension\Context\MinkContext;

use Meetup\Authentication;
use Meetup\GroupHome;

/**
 * Features context.
 *
 * Based on behat.yml, a basic version of this file can be generated by calling "./bin/behat --init"
 */
class FeatureContext extends BehatContext
{
    /**
     * Initializes context.
     * Every scenario gets it's own context object.
     *
     * @param array $parameters context parameters (set them up through behat.yml)
     */
    public function __construct(array $parameters)
    {
        // Initialize your context here
        $this->useContext("mink", new MinkContext());
        $this->useContext("authentication", new Authentication());
        $this->useContext("groupHome", new GroupHome());
    }
}
